### ISSUE TITLE
As a service author, I want binding credentials provided by the service broker to be stored in CredHub

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/spring-cloud-app-broker#119]
GIVEN a service broker is deployed using the manifest: 
```
spring:
  cloud:
    appbroker: 
      services:
        service-name: service-with-custom-binding-handler
        plan-name: standard 
        apps:
        - name: instance-to-bind-with
          path: classpath:demo.jar 
```
AND a service instance is provisioned
WHEN a `bind-service` request is received from the platform
THEN the `credentials` field of the `bind-service` response is populated by the implementing broker
AND the  credentials are stored in CredHub using the `cloud-foundry-extensions` module
AND the `credentials` field is populated with CredHub reference

CredHub credential creation will be conditional on the presence of a configure `CredhubTemplate`
