### ISSUE TITLE
Deploy all the backing apps of a given service to a single space dedicated to the SI

### ISSUE THREAD

**Issue by AlbertoImpl** [spring-cloud-incubator/spring-cloud-app-broker#133]
`GIVEN` The application manifest contains:
```
spring:
  cloud:
    appbroker:
      services:
        target: 
        - name: SpacePerServiceInstance
        apps: 
        - name: my-app
      deployer:
        cloudfoundry:
          api-host: api.cf.example.org
          default-org: my-broker-org
          default-space: development
```
`WHEN` a service instance is created
`THEN` the a backing app is deployed with the following properties (where `[SI GUID]` is the GUID assigned by the platform to the created service instance):

org: `my-broker-org`
space: `[SI GUID]`
app name: `my-app`
app route host: `my-app-[SI GUID]`

**Comment by AlbertoImpl** [comment]
Moving `target` one level up, since it will make the design cleaner and there is no need to deploy each app on a separate space.
Now we could have `createTarget` and `deleteTarget` methods in the `AppBrokerDeployer` interface to perform the creation and deletion of spaces/namespaces at the beginning/ending of each flow.

**Comment by csterwa** [comment]
@albertoimpl I noticed this is in To Be Refined column but I thought this was already implemented? Am I incorrect?

**Comment by AlbertoImpl** [comment]
Today we deploy each independent app into a specific space.
This story will move that one level up and create the space, then try to do the deployment of the applications.
It will help us organize the code a bit better, since, there is no need for deploying each app into a different space.
In other words, from what we have today:
```
spring:
  cloud:
    appbroker:
      services:
        apps: 
        - name: my-app
          target: 
          - name: SpacePerServiceInstance
```
to
```
spring:
  cloud:
    appbroker:
      services:
        target: 
        - name: SpacePerServiceInstance
        apps: 
        - name: my-app
```
