### ISSUE TITLE
As service author, I can describe in a manifest services that get created and bound to a backing app

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud-incubator/spring-cloud-app-broker#14]
`GIVEN` The application manifest contains:
```
spring:
  cloud
    appbroker:
      services: 
        apps:
        - name: app-with-services
          services:
          - service-instance-name: my-db-service
            name: mysqldb
            plan: small
            parameters: 
              key: value
          - service-instance-name: my-messaging-service
            name: rabbitmq
            plan: medium
            parameters: 
              key: value
```
`WHEN` a service instance is created
`THEN` backing service instances with the given names and plans should be created (asynchronously if required by the service) and bound to the `app-with-services` app
