### ISSUE TITLE
As service author, I can describe in a manifest services that get updated when a service instance is updated

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud-incubator/spring-cloud-app-broker#163]
`GIVEN` The application manifest contains:
```
spring:
  cloud
    appbroker:
      services: 
        apps:
        - name: app-with-services
          services:
          - service-instance-name: my-db-service
            name: mysqldb
            plan: small
          - service-instance-name: my-messaging-service
            name: rabbitmq
            plan: medium
```
`WHEN` a service instance is updated with `cf update-service -c '{"key":"value"}'`
`THEN` backing service instances `my-db-service` and `my-messaging-service` are updated (asynchronously if required by the managing service broker) with appropriate parameter mapping (as supported by #139) 

**Note:** services instances can be updated with a change to the SI name, plan, or parameters. Among these attributes, only backing service instance parameters can potentially be affected by an update to the managed service instance. An update to the managed SI will only result in an update of a backing SI if the mapping of incoming parameters (from e.g. `cf update-service -c`) to backing SI parameters results in parameters being configured for the backing SI.
