### ISSUE TITLE
As a service author, I can describe in a manifest that OAuth2 credentials should be generated for a deployed application

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud-incubator/spring-cloud-app-broker#17]
`GIVEN` The application manifest contains:

```
spring:
  cloud:
    appbroker: 
      services: 
        apps:
        - name: my-app
          credentials-providers:
          - name: SpringSecurityOAuth2
            args: 
            - identity-zone-subdomain: my-identity-zone
```

`WHEN` a service instance is created
`THEN` the application `my-app` has a `SPRING_APPLICATION_JSON` environment variable containing the values:

```
{
"security.oauth2.client.access-token-uri: "https://my-identity-zone.uaa.example.com/oauth/token", 
"security.oauth2.client.client-id": "my-app-[SI GUID]", 
"security.oauth2.client.client-secret": "a-generated-secret"
}
```

`AND` a client with the ID and secret will be stored in UAA within the specified identity zone
`AND` the client will be deleted from UAA when the service instance is deleted

If the `args: identity-zone-subdomain` configuration property is omitted, then the client is created in the default UAA identity zone.
