### ISSUE TITLE
As service author, I can describe in a manifest services that get deleted when a service instance is deleted

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud-incubator/spring-cloud-app-broker#76]
`GIVEN` The application manifest contains:
```
spring:
  cloud
    appbroker:
      services: 
        apps:
        - name: app-with-services
          services:
          - service-instance-name: my-db-service
            name: mysqldb
            plan: small
          - service-instance-name: my-messaging-service
            name: rabbitmq
            plan: medium
```
`WHEN` a service instance is deleted
`THEN` backing service instances `my-db-service` and `my-messaging-service` are deleted  (asynchronously if required by the managing service broker) along with the backing app
