### ISSUE TITLE
As a service author, I can describe in a manifest the app that gets deployed for each service in the catalog

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud-incubator/spring-cloud-app-broker#77]
`GIVEN:` a service broker catalog configuration that exposes multiple services and plans

```
spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: first-service
          plans:
          - id: first-plan
          - id: second-plan
        services:
        - id: second-service
          plans:
          - id: simple-plan
```

`AND:` an app broker manifest that describes applications for each service and plan

```
spring:
  cloud:
    appbroker:
      services: 
        - id: first-service
           plan-id: first-plan
           apps:
           - name: first-service-first-plan-app1
              path: classpath:demo.jar
           - name: first-service-first-plan-app2
              path: classpath:demo.jar      
        - id: first-service
           plan-id: second-plan
           apps:
           - name: first-service-second-plan-app
              path: classpath:demo.jar
        - id: second-service
           plan-id: simple-plan
           apps:
           - name: second-service-simple-plan-app
              path: classpath:demo.jar
```

`THEN`: the appropriate app(s) will be deployed depending on the ID and plan of the service instance being created
