### ISSUE TITLE
As a service author, I want to configure a whitelist of parameters mapped to backing app environment variables

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud-incubator/spring-cloud-app-broker#91]
`GIVEN` that a backing app is specified with a parameters transformer that maps parameters to backing app environment variables
`AND` the parameters transformer is configured to allow only listed parameters to be transformed

```
spring:
  cloud:
    appbroker:
      app:
        parameters-transformers: 
        - name: EnvironmentMapping
           args: 
           - include: parameter1,parameter2
```

`THEN` I can see the SPRING_APPLICATION_JSON environment variable for the backing app `mapping-app` containing only the white-listed parameters:

```
"{"parameter1": "value1", "parameter2": "value2"
```
